export const data = [
  {
    ID: 1,
    type: "Irene, Go Home! (Irena do domu!)",
    size: 5,
    beds: 3,
    bath: 4,
    price: "$539635.03",
    area: "Pawling",
    city: "Minneapolis",
    province: "Minnesota",
    images: [
      "http://dummyimage.com/178x100.png/cc0000/ffffff",
      "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/249x100.png/ff4444/ffffff",
      "http://dummyimage.com/146x100.png/dddddd/000000",
      "http://dummyimage.com/234x100.png/dddddd/000000",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 2,
    type: "Book of Stars, The",
    size: 60,
    beds: 4,
    bath: 4,
    price: "$497645.19",
    area: "Mcguire",
    city: "San Antonio",
    province: "Texas",
    images: [
      "http://dummyimage.com/149x100.png/dddddd/000000",
      "http://dummyimage.com/193x100.png/dddddd/000000",
      "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/203x100.png/cc0000/ffffff",
      "http://dummyimage.com/208x100.png/dddddd/000000",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 3,
    type: "Circus, The",
    size: 6,
    beds: 1,
    bath: 4,
    price: "$294924.16",
    area: "Morning",
    city: "Springfield",
    province: "Illinois",
    images: [
      "http://dummyimage.com/177x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/138x100.png/dddddd/000000",
      "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/124x100.png/ff4444/ffffff",
      "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 4,
    type: "Soap Girl",
    size: 97,
    beds: 1,
    bath: 1,
    price: "$881967.08",
    area: "Melby",
    city: "Honolulu",
    province: "Hawaii",
    images: [
      "http://dummyimage.com/185x100.png/cc0000/ffffff",
      "http://dummyimage.com/225x100.png/dddddd/000000",
      "http://dummyimage.com/113x100.png/cc0000/ffffff",
      "http://dummyimage.com/183x100.png/ff4444/ffffff",
      "http://dummyimage.com/122x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 5,
    type: "Way of War, The",
    size: 86,
    beds: 4,
    bath: 2,
    price: "$368510.16",
    area: "Ridge Oak",
    city: "Madison",
    province: "Wisconsin",
    images: [
      "http://dummyimage.com/114x100.png/cc0000/ffffff",
      "http://dummyimage.com/140x100.png/cc0000/ffffff",
      "http://dummyimage.com/215x100.png/cc0000/ffffff",
      "http://dummyimage.com/150x100.png/dddddd/000000",
      "http://dummyimage.com/224x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 6,
    type: "Space Movie, The",
    size: 52,
    beds: 1,
    bath: 1,
    price: "$681524.64",
    area: "3rd",
    city: "Tucson",
    province: "Arizona",
    images: [
      "http://dummyimage.com/102x100.png/cc0000/ffffff",
      "http://dummyimage.com/224x100.png/dddddd/000000",
      "http://dummyimage.com/145x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/180x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/239x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 7,
    type: "Son of Rambow",
    size: 11,
    beds: 1,
    bath: 1,
    price: "$606366.13",
    area: "Commercial",
    city: "Brea",
    province: "California",
    images: [
      "http://dummyimage.com/115x100.png/ff4444/ffffff",
      "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/158x100.png/ff4444/ffffff",
      "http://dummyimage.com/106x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 8,
    type: "Deuce Bigalow: European Gigolo",
    size: 49,
    beds: 3,
    bath: 3,
    price: "$260118.22",
    area: "Chinook",
    city: "Springfield",
    province: "Illinois",
    images: [
      "http://dummyimage.com/139x100.png/ff4444/ffffff",
      "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/217x100.png/ff4444/ffffff",
      "http://dummyimage.com/191x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 9,
    type: "Son of Frankenstein",
    size: 12,
    beds: 4,
    bath: 4,
    price: "$541139.41",
    area: "Susan",
    city: "Birmingham",
    province: "Alabama",
    images: [
      "http://dummyimage.com/222x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/236x100.png/cc0000/ffffff",
      "http://dummyimage.com/169x100.png/ff4444/ffffff",
      "http://dummyimage.com/131x100.png/cc0000/ffffff",
      "http://dummyimage.com/133x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 10,
    type: "For the Moment",
    size: 100,
    beds: 2,
    bath: 2,
    price: "$729321.32",
    area: "Sugar",
    city: "Punta Gorda",
    province: "Florida",
    images: [
      "http://dummyimage.com/106x100.png/dddddd/000000",
      "http://dummyimage.com/186x100.png/dddddd/000000",
      "http://dummyimage.com/165x100.png/dddddd/000000",
      "http://dummyimage.com/236x100.png/dddddd/000000",
      "http://dummyimage.com/217x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 11,
    type: "Sylvia Scarlett",
    size: 36,
    beds: 2,
    bath: 2,
    price: "$884481.33",
    area: "Arizona",
    city: "Des Moines",
    province: "Iowa",
    images: [
      "http://dummyimage.com/247x100.png/cc0000/ffffff",
      "http://dummyimage.com/154x100.png/ff4444/ffffff",
      "http://dummyimage.com/110x100.png/cc0000/ffffff",
      "http://dummyimage.com/231x100.png/dddddd/000000",
      "http://dummyimage.com/154x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 12,
    type: "Switching Goals",
    size: 97,
    beds: 2,
    bath: 4,
    price: "$347014.79",
    area: "Kings",
    city: "Las Cruces",
    province: "New Mexico",
    images: [
      "http://dummyimage.com/238x100.png/ff4444/ffffff",
      "http://dummyimage.com/134x100.png/dddddd/000000",
      "http://dummyimage.com/155x100.png/dddddd/000000",
      "http://dummyimage.com/167x100.png/ff4444/ffffff",
      "http://dummyimage.com/227x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 13,
    type: "Toto le héros",
    size: 45,
    beds: 2,
    bath: 4,
    price: "$438433.71",
    area: "Burrows",
    city: "Minneapolis",
    province: "Minnesota",
    images: [
      "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/207x100.png/cc0000/ffffff",
      "http://dummyimage.com/244x100.png/dddddd/000000",
      "http://dummyimage.com/235x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/207x100.png/ff4444/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 14,
    type: "Justin Bieber's Believe",
    size: 42,
    beds: 3,
    bath: 1,
    price: "$978403.93",
    area: "Judy",
    city: "Pensacola",
    province: "Florida",
    images: [
      "http://dummyimage.com/243x100.png/dddddd/000000",
      "http://dummyimage.com/100x100.png/dddddd/000000",
      "http://dummyimage.com/233x100.png/cc0000/ffffff",
      "http://dummyimage.com/125x100.png/ff4444/ffffff",
      "http://dummyimage.com/218x100.png/dddddd/000000",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 15,
    type: "Romy and Michele's High School Reunion",
    size: 21,
    beds: 3,
    bath: 3,
    price: "$332899.01",
    area: "Sullivan",
    city: "Bryan",
    province: "Texas",
    images: [
      "http://dummyimage.com/114x100.png/ff4444/ffffff",
      "http://dummyimage.com/139x100.png/dddddd/000000",
      "http://dummyimage.com/151x100.png/ff4444/ffffff",
      "http://dummyimage.com/228x100.png/dddddd/000000",
      "http://dummyimage.com/145x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 16,
    type: "Boy Friend, The",
    size: 57,
    beds: 2,
    bath: 1,
    price: "$769295.84",
    area: "Pepper Wood",
    city: "Vienna",
    province: "Virginia",
    images: [
      "http://dummyimage.com/165x100.png/cc0000/ffffff",
      "http://dummyimage.com/108x100.png/ff4444/ffffff",
      "http://dummyimage.com/226x100.png/cc0000/ffffff",
      "http://dummyimage.com/141x100.png/dddddd/000000",
      "http://dummyimage.com/116x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 17,
    type: "Perfect Sense",
    size: 40,
    beds: 1,
    bath: 1,
    price: "$581956.58",
    area: "Holy Cross",
    city: "Chicago",
    province: "Illinois",
    images: [
      "http://dummyimage.com/196x100.png/dddddd/000000",
      "http://dummyimage.com/212x100.png/ff4444/ffffff",
      "http://dummyimage.com/147x100.png/ff4444/ffffff",
      "http://dummyimage.com/158x100.png/ff4444/ffffff",
      "http://dummyimage.com/194x100.png/5fa2dd/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 18,
    type: "American Gigolo",
    size: 20,
    beds: 3,
    bath: 2,
    price: "$369403.87",
    area: "Kipling",
    city: "Saint Louis",
    province: "Missouri",
    images: [
      "http://dummyimage.com/187x100.png/ff4444/ffffff",
      "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/151x100.png/cc0000/ffffff",
      "http://dummyimage.com/132x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/142x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 19,
    type: "Knack ...and How to Get It, The",
    size: 38,
    beds: 2,
    bath: 3,
    price: "$871855.40",
    area: "Cardinal",
    city: "New York City",
    province: "New York",
    images: [
      "http://dummyimage.com/194x100.png/cc0000/ffffff",
      "http://dummyimage.com/179x100.png/cc0000/ffffff",
      "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/250x100.png/cc0000/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
  {
    ID: 20,
    type: "Alphabet Killer, The",
    size: 57,
    beds: 1,
    bath: 1,
    price: "$684597.49",
    area: "Rusk",
    city: "Long Beach",
    province: "California",
    images: [
      "http://dummyimage.com/111x100.png/ff4444/ffffff",
      "http://dummyimage.com/170x100.png/cc0000/ffffff",
      "http://dummyimage.com/238x100.png/ff4444/ffffff",
      "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
      "http://dummyimage.com/106x100.png/ff4444/ffffff",
    ],
    amenities: [
      "bifurcated",
      "matrices",
      "Seamless",
      "Organized",
      "Horizontal",
      "encoding",
      "Reactive",
      "Future-proofed",
    ],
    details:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad quam asperiores aperiam pariatur ut labore hic voluptatibus. Ipsam dolorum incidunt facilis similique nostrum nesciunt, perspiciatis dignissimos quaerat ullam cum.",
  },
];
